from scripts.motion_detector_ROS_client_format import ClientFormat
#from scripts.detector_manager_ROS_server_format import ServerFormat
#
#from serverclient_bak.motion_detector_ROS_client_format import ClientFormat